org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.197
loader_version_range=[1,)

mod_id=bakeries
mod_name=Bakeries
mod_license=All Rights Reserved

mod_version=1.21.1-NeoForge-1.0.0-beta4
mod_group_id=com.renyigesai.bakeries
mod_authors=Renyigesai,1-weibai-1,NeptuneTADASHI,zhifan
mod_description=This is a Baker yummy mod.

#Jei
mc_version=1.21.1
jei_version=19.25.0.322
#Jade
jade_version=15.10.3+neoforge

rcg_lib_version = 1.0.2-beta