
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false


minecraft_version=1.20.1

minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.11
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=bakeries
mod_name=Bakeries
mod_license=All Rights Reserved
mod_version=1.20.1Forge-1.0.0
mod_group_id=com.renyigesai.bakery
mod_authors=Renyigesai,1-weibai-1
mod_description=This is a Baker yummy mod.

pack_format_number=15
patchouli_forge_version=1.20.1-84-FORGE

