// 定义仓库  
repositories {
    maven {
        url "https://maven.aliyun.com/repository/public"
    }
    maven {
        url "https://cursemaven.com"
    }
    maven {
        name = "BlameJared Maven"
        url = "https://maven.blamejared.com"
    }
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    maven {
        name = "Progwml6 maven"
        url = "https://dvs1.progwml6.com/files/maven/"
    }
    maven { url "https://maven.ryanliptak.com/" }

    maven { // Patchouli
        url "https://maven.blamejared.com"
    }
    maven { url = "https://mvn.devos.one/snapshots/" }
    maven {
        url "https://maven2.bai.lol"
        content {
            includeGroup "lol.bai"
            includeGroup "mcp.mobius.waila"
        }
    }
    mavenLocal()
    mavenCentral()
}

// 定义依赖  
dependencies {
    // WorldEdit 依赖  
    implementation fg.deobf("curse.maven:worldedit-225608:4586218")

    compileOnly fg.deobf("curse.maven:jade-324717:5876199")
    runtimeOnly fg.deobf("curse.maven:jade-324717:5876199")

    // CraftTweaker 依赖  
    compileOnly fg.deobf('com.blamejared.crafttweaker:CraftTweaker-forge-1.20.1:14.0.17')
    runtimeOnly fg.deobf('com.blamejared.crafttweaker:CraftTweaker-forge-1.20.1:14.0.17')

    // JEI 依赖
    compileOnly fg.deobf("mezz.jei:jei-1.20.1-common-api:15.20.0.105")
    compileOnly fg.deobf("mezz.jei:jei-1.20.1-forge-api:15.20.0.105")
    runtimeOnly fg.deobf("mezz.jei:jei-1.20.1-forge:15.20.0.105")
    //Apple_skin 依赖
    compileOnly fg.deobf("squeek.appleskin:appleskin-forge:mc1.20.1-2.5.1:api")
    runtimeOnly fg.deobf("squeek.appleskin:appleskin-forge:mc1.20.1-2.5.1")
    //Patchouli 依赖
    compileOnly fg.deobf("vazkii.patchouli:Patchouli:[1.20.1-84-FORGE]:api")
    runtimeOnly fg.deobf("vazkii.patchouli:Patchouli:[1.20.1-84-FORGE]")
}

// Minecraft 配置  
minecraft {
    runs {
        client {
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
        }
        server {
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
        }
        data {
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
        }
    }
}